"""
Django settings for PKSF project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
from datetime import datetime, timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3t*l)lib!6*5yo)_6yp(uv-(w5@gt2)_=fe@v+qr2y%%y^v+vu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# CORS WHITELIST
# CORS_ORIGIN_WHITELIST = [
#     "http://192.168.1.207:3000",
#     "https://relaxed-curie-e9a516.netlify.app",
#     "http://127.0.0.1:8080"
# ]
CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'farm.apps.FarmConfig',
    'farming.apps.FarmingConfig',
    'devices.apps.DevicesConfig',
    'processing.apps.ProcessingConfig',
    'users.apps.UsersConfig',
    'rest_framework',
    'rest_framework_jwt',
    'drf_yasg',
    'corsheaders',
    'drf_api_logger'
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'drf_api_logger.middleware.api_logger_middleware.APILoggerMiddleware', 

]

ROOT_URLCONF = 'PKSF.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PKSF.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'pksfdb',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '9999',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Dhaka'


USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

JWT_TIMEOUT = timedelta(days=1, hours=0)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'users.api.authentication.SafeJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),

}


SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS':
        {
            "Auth Token eg [Bearer (JWT)]": {
                "type": "apiKey",
                "name": "Authorization",
                "in": "header"

            }
        }
}


# LOGGING ={
#     'version':1,
#     'loggers':{
#         'django':{
#             'handlers':['file','file2'],
#             'level':'DEBUG'
#         }
#     },
#     'handlers':{
#         'file':{
#             'level':'INFO',
#             'class': 'logging.FileHandler',
#             'filename':'./logs/debug5.log',
#             'formatter':'simpleRe',
#         },
#         'file2':{
#             'level':'DEBUG',
#             'class': 'logging.FileHandler',
#             'filename':'./logs/debug6.log',
#             'formatter':'simpleRe',
#         }
#     },
#     'formatters':{
#         'simpleRe': {
#             'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
#             'style': '{',
#         }
#
#     }
# }

DRF_API_LOGGER_DATABASE = True

EMAIL_HOST = 'smtp.gmail.com'           # you must Allow less secure apps: ON from google settings
EMAIL_HOST_USER = 'srdl.doict@gmail.com'
EMAIL_HOST_PASSWORD = 'Pass@2019'
EMAIL_PORT = '587'
EMAIL_USE_TLS = True